name: Deploy Strapi via SSH

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy Strapi"
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key

      - name: SSH and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${INSTANCE_IP} '
          cd /srv/strapi/forstrapi/row
          sudo git pull origin master
          sudo yarn install
          sudo pm2 restart saketh
          '
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          USER_NAME: ${{ secrets.USER_NAME }}
          INSTANCE_IP: ${{ secrets.INSTANCE_IP }}
