name: SSH into EC2

on:
  workflow_dispatch:

env:
  PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY}}
  INSTANCE_IP: ${{ secrets.INSTANCE_IP }}
  USER_NAME: ${{ secrets.SSH_USERNAME }}

jobs:
  ssh_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start SSH agent and add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ env.PRIVATE_KEY }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ env.INSTANCE_IP }}
          username: ${{ env.USER_NAME }}
          key: ${{ env.PRIVATE_KEY }}
          script: |
            cd /srv/strapi/forstrapi/row
            sudo git pull origin master
            sudo yarn install
            sudo pm2 restart saketh
            EOF
        env:
          INSTANCE_IP: ${{ env.INSTANCE_IP }}
          USER_NAME: ${{ env.USER_NAME }}
