name: SSH into EC2

on:
  workflow_dispatch:

env:
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  INSTANCE_IP: ${{ secrets.INSTANCE_IP }}
  USER_NAME: ${{ secrets.USER_NAME }}

jobs:
  ssh_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $INSTANCE_IP >> ~/.ssh/known_hosts

      - name: SSH and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $USER_NAME@$INSTANCE_IP << 'EOF'
          cd /srv/strapi/forstrapi/row
          sudo git pull origin master
          sudo yarn install
          sudo pm2 restart saketh
          EOF
        env:
          INSTANCE_IP: ${{ env.INSTANCE_IP }}
          USER_NAME: ${{ env.USER_NAME }}
