name: Deploy via SSH

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest

    env:
      INSTANCE_IP: ${{ steps.terraform.outputs.INSTANCE_IP }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Wait for instance to be ready
        run: sleep 60

      - name: Run commands on EC2 instance
        run: |
          ssh -o StrictHostKeyChecking=no ${{ env.SSH_USERNAME }}@${{ env.INSTANCE_IP }} << 'EOF'
          cd /srv/strapi/forstrapi/row
          git pull origin master
          yarn install
          pm2 restart saketh
          EOF
