name: Deploy via SSH

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest

    env:
      INSTANCE_IP: "100.26.55.160"
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      

      - name: Run commands on EC2 instance
        run: |
          ssh -o StrictHostKeyChecking=no -o ForwardAgent=yes ***@100.26.55.160 << 'EOF'
          cd /srv/strapi/forstrapi/row
          sudo git pull origin master
          sudo yarn install
          sudo pm2 restart saketh
          EOF
