name: ssh-into-aws-ec2

on:
  push:
    branches: [ "master" ]
  
env:
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  USER_NAME: ${{ secrets.USER_NAME }}
  INSTANCE_IP: ${{ secrets.INSTANCE_IP }}
  
permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$PRIVATE_KEY" > ~/.ssh/github-actions-key
          chmod 600 ~/.ssh/github-actions-key
          cat >>~/.ssh/config <<END
          Host ec2
            HostName $INSTANCE_IP
            User $USER_NAME
            IdentityFile ~/.ssh/github-actions-key
            StrictHostKeyChecking no
          END
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          USER_NAME: ${{ secrets.USER_NAME }}
          INSTANCE_IP: ${{ secrets.INSTANCE_IP }}
          
      - name: List home directory
        run: ssh ec2 'ls -la'
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          USER_NAME: ${{ secrets.USER_NAME }}
          INSTANCE_IP: ${{ secrets.INSTANCE_IP }}
