name: Terraform

on:
  workflow_dispatch:
   inputs:
      destroy:
        required: true
        type: string
jobs:     
   destroy:
    name: "Terraform Destroy"
    runs-on: self-hosted
    if: github.event.inputs.destroy == 'true'
    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.11 # Specify your Terraform version here
          terraform_wrapper: false
           
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color  

      - name: Terraform Destroy
        run: terraform destroy -auto-approve  
