name: Terraform

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Specify the action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
jobs:
  terraform:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: .
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.11
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Terraform Action
        run: |
          if [ "${{ github.event.inputs.action }}" == "apply" ]; then
            terraform plan -no-color
            terraform apply -auto-approve
            echo "done apply"
          elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
            terraform plan -no-color
            terraform destroy -auto-approve
          else
            echo "Invalid action specified"
            exit 1
          fi
